# Generated by Django 3.0.3 on 2020-05-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('routine', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('quote', models.CharField(max_length=32)),
                ('inittime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('routine', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineRecord',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('manualend', models.BooleanField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Routine')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='users',
            field=models.ManyToManyField(to='backend.UserInfo'),
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=160)),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=6)),
                ('users', models.ManyToManyField(to='backend.UserInfo')),
            ],
        ),
    ]
