# Generated by Django 3.0.3 on 2020-05-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
    ]
