# Generated by Django 3.0.3 on 2020-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200510_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='inittime',
            field=models.DateTimeField(),
        ),
    ]
